<?php

/**
 * @file
 * Hook implementations, callbacks form OpenID SSO.
 */

/**
 * Implementation of hook_strongarm().
 */
function openid_sso_strongarm() {
  return array (
    // No email verification as users can only sign in from trusted provider.
    'user_email_verification' => 0,
    // We must allow user registration otherwise OpenID will refuse to register
    // user. We will suppress user/register in hook_menu_alter().
    'user_register' => '1',
  );
}

/**
 * Implementation of hook_menu_alter().
 */
function openid_sso_menu_alter(&$items) {
  // Disable user registration page to suppress direct registration.
  $items['user/register']['page callback'] = 'openid_sso_register_redirect';
  // Override the user page callback to replace it with our own login form.
  $items['user']['page callback'] = 'openid_sso_user_page';
}

/**
 * Custom menu callback for user/ page.
 */
function openid_sso_user_page() {

  // If user is logged in, just pass on to original user page.
  global $user;
  if ($user->uid) {
    return user_page();
  }

  // If there is an identifier passed in in GET request, present login form.
  if ($_GET['identifier']) {
    return drupal_get_form('openid_sso_login_form', $_GET['identifier']);
  }

  // Otherwise redirect to trusted OpenID Provider.
  openid_sso_register_redirect();
}

/**
 * Redirect to registration page on provider.
 */
function openid_sso_register_redirect() {
  $provider = variable_get('openid_sso_provider', '');
  $relying_party = urlencode(url('', array('absolute' => TRUE)));
  drupal_goto($provider['url'], "q=user/register&relying_party=$relying_party");
}

/**
 * Simplified login form.
 *
 * Offer simple text field for user name. On submit, tack user name to the end
 * of OpenID Provider URL and redirect to begin athentication handshake.
 *
 * Compare to openid_form_alter().
 */
function openid_sso_login_form($identifier) {
  drupal_add_js(drupal_get_path('module', 'openid_sso') .'/openid_sso.js');
  $provider = variable_get('openid_sso_provider', 'SSO Web');

  $form = array();
  $form['#attributes'] = array('class' => 'auto-submit');
  $form['message']['#value'] = '<h3>'. t('Hello @name &ndash; you are being logged in automatically', array('@name' => $_GET['identifier'])) .'</h3>';
  $form['message']['#value'] .= '<p>'. t('If page does not redirect within 3 seconds, click "Log in" button below.') .'</p>';

  $form['openid_identifier'] = array(
    '#type' => 'textfield',
    '#default_value' => check_plain(urldecode($_GET['identifier'])),
    '#maxlength' => 255,
    // Use prefix/suffix instead of #attributes as we'd like to hide the label, too.
    '#prefix' => '<div style="display:none">',
    '#suffix' => '</div>',
  );
  $form['#validate'] = array('openid_sso_login_form_validate');
  $form['openid.return_to'] = array('#type' => 'hidden', '#value' => url('openid/authenticate', array('absolute' => TRUE, 'query' => drupal_get_destination())));
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Log in'),
  );
  return $form;
}

/**
 * Submit hook for openid_sso_login_form().
 *
 * Compare to openid_login_validate().
 */
function openid_sso_login_form_validate($form, &$form_state) {
  $return_to = $form_state['values']['openid.return_to'];
  if (empty($return_to)) {
    $return_to = url('', array('absolute' => TRUE));
  }
  $provider = variable_get('openid_sso_provider', '');
  openid_begin($provider['url'] .'/openid/'. urlencode($form_state['values']['openid_identifier']), $return_to, $form_state['values']);
}
