<?php

/**
 * Implementation hook_menu_alter().
 */
function osso_relying_menu_alter(&$items) {

  foreach (array('user', 'logout', 'node/add/story') as $path) {
    $items[$path]['menu_name'] = 'features';
    $items[$path]['type'] = MENU_NORMAL_ITEM;
  }

  $items['user']['title callback'] = 'osso_relying_user_menu_title';
  $items['user/register']['title callback'] = 'osso_relying_register_menu_title';
}

/**
 * Custom title callback.
 */
function osso_relying_user_menu_title() {
  global $user;
  if ($user->uid) {
    return t('Hello @user', array('@user' => $user->name));
  }
  $provider = variable_get('openid_sso_provider', array());
  return t('Log in with your !provider ID', array('!provider' => $provider['name']));
}

/**
 * Custom title callback.
 */
function osso_relying_register_menu_title() {
  return t('Sign up');
}
