<?php

/**
 * Implementation hook_menu_alter().
 */
function osso_relying_menu_alter(&$items) {

  foreach (array('user', 'logout', 'node/add/story') as $path) {
    $items[$path]['menu_name'] = 'features';
    $items[$path]['type'] = MENU_NORMAL_ITEM;
  }
  $items['user/%user_uid_optional']['page callback'] = 'osso_relying_user_view';
  $items['user']['title callback'] = 'osso_relying_user_menu_title';
  $items['user/register']['title callback'] = 'osso_relying_register_menu_title';
}

/**
 * Custom user callback, redirect to OP.
 */
function osso_relying_user_view($account) {
  $provider = variable_get('openid_sso_provider', '');
  if ($provider['url'] && !empty($account->name)) {
    drupal_goto($provider['url'], 'q=user/'. urlencode($account->name));
  }
  else {
    return user_view($account);
  }
}

/**
 * Custom title callback.
 */
function osso_relying_user_menu_title() {
  global $user;
  if ($user->uid) {
    return t('Hello @user', array('@user' => $user->name));
  }
  $provider = variable_get('openid_sso_provider', array());
  return t('Log in with your !provider ID', array('!provider' => $provider['name']));
}

/**
 * Custom title callback.
 */
function osso_relying_register_menu_title() {
  return t('Sign up');
}
